### ISSUE TITLE
camera calibration

### ISSUE THREAD

**Issue by twmht** [mvirgo/Advanced-Lane-Lines#1]
@mvirgo 

In the pipeline, you obtain the camera calibration by chessboard calibration images .

```
cal_image_loc = glob.glob('camera_cal/*.jpg')
```

But I did not find `camera_cal` in the repo.

when can I find that?

**Comment by mvirgo** [comment]
You can find it in Udacity's main repository [here](https://github.com/udacity/CarND-Advanced-Lane-Lines/tree/master/camera_cal)

**Comment by twmht** [comment]
@mvirgo 

thanks
